version: '3.7'

services:
  nginx:
    build:
      context: ./nginx
    container_name: webserver
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /ssl/ssl_stat/conf:/etc/letsencrypt
      - /ssl/ssl_stat/www:/var/www/certbot
      - icons:/app/static/icons
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - flaskapp
    networks:
      - webnet
    restart: always

  certbot:
    build:
      context: ./certbot
    container_name: certbot
    volumes:
      - /ssl/ssl_stat/conf:/etc/letsencrypt
      - /ssl/ssl_stat/www:/var/www/certbot
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    entrypoint: /bin/sh -c "certbot renew --webroot -w /var/www/certbot"
    networks:
      - webnet

  timescaledb:
    image: timescale/timescaledb:latest-pg16
    container_name: timescaledb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: YOUR_DB_PASSWORD
      POSTGRES_USER: postgres
      POSTGRES_DB: liveinternet
    volumes:
      - db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  backup:
    build:
      context: ./backup
    environment:
      DB_NAME: liveinternet
      DB_USER: postgres
      DB_HOST: timescaledb
      DB_PORT: 5432
      DB_PASSWORD: YOUR_DB_PASSWORD
      ACCESS_KEY: YOUR_SELECTEL_ACCESS_KEY
      SECRET_KEY: YOUR_SELECTEL_SECRET_KEY
    volumes:
      - backup-data:/backup-data
    depends_on:
      - timescaledb
    deploy:
      restart_policy:
        condition: on-failure

  fastapiapp:
    build: ./api
    container_name: liveinternet_api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
      - shared_data:/app/data
    depends_on:
      - timescaledb
    restart: unless-stopped
    environment:
      DB_HOST: timescaledb
      DB_PORT: 5432
      DB_USER: api
      DB_PASSWORD: YOUR_API_PASSWORD
      DB_NAME: liveinternet
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  parser:
    build: ./parser
    container_name: liveinternet_parser
    volumes:
      - ./parser:/app
      - shared_data:/app/data
      - icons:/app/icons
    depends_on:
      - timescaledb
    restart: unless-stopped
    environment:
      DB_HOST: timescaledb
      DB_PORT: 5432
      DB_USER: parser
      DB_PASSWORD: YOUR_PARSER_PASSWORD
      DB_NAME: liveinternet
    command: [ "/bin/bash", "/app/start.sh" ]

  flaskapp:
    build: ./web
    container_name: liveinternet_web
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
      FLASK_APP: app.py
    volumes:
      - ./web:/app
      - icons:/app/static/icons
    depends_on:
      - fastapiapp
    command: flask run --host=0.0.0.0
    networks:
      - webnet

volumes:
  db:
  shared_data:
  icons:
  backup-data:

networks:
  webnet:
    driver: bridge
